config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :articles do
  	resource :comments, only: [:create, :destroy]
    collection do
      get  :ajax_article_list
    end
  end
  get '/top' => 'homes#top'
  get '/about' => 'homes#about'
  root 'homes#top'

  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories, dependent: :destroy
	has_many :categories, through: :article_categories
	has_many :comments

	scope :from_category, -> (category_id)  { where(id: article_ids = ArticleCategory.where(category_id: category_id).select(:article_id))}

	validates :title, presence: true
	validates :error_name, presence: true
	validates :factor, presence: true
	validates :introduction, presence: true
	validates :result, presence: true

	def self.search_by_title(titles)
		articles = Article.where(is_completed: true).where('title LIKE ?', "%#{titles}%")
	end


	def save_categories(tags)
		current_tags = self.categories.pluck(:category_name) unless self.categories.nil?
		old_tags = current_tags - tags
		new_tags = tags - current_tags

		# Destroy old taggings:
		old_tags.each do |old_name|
			self.categories.delete Category.find_by(category_name:old_name)
		end

		# Create new taggings:
		new_tags.each do |new_name|
			article_category = Category.find_or_create_by(category_name:new_name)
			self.categories << article_category
		end
	end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action  :set_article_tags_to_gon, only: [:edit]

  # GET /articles
  # GET /articles.json
  def index
    #@articles = Article.all
    if params[:category_id]
      @selected_category = Category.find(params[:category_id])
      # @articles= Article.where(is_completed: true).page(params[:page])
      @articles= Article.from_category(params[:category_id]).where(is_completed: true).page(params[:page])
    else
      @articles= Article.where(is_completed: true).page(params[:page])
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    #@user = @articles.user
    @article= Article.find(params[:id])
    if params[:category_id]
      @selected_category = Category.find(params[:category_id])
      @articles= Article.from_category(params[:category_id]).page(params[:page])
    else
      @article= Article.find(params[:id])
    end
    @comment = Comment.new
    @comments = @article.comments
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article= Article.find(params[:id])
    @category_list = @article.categories.pluck(:category_name).join(",")
    if @article.user_id != current_user.id
       redirect_back(fallback_location: root_path)
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article= current_user.articles.build(article_params)
    @article.user_id != current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }

      end

      if @article.save
        if params[:button1]
           @article.update(is_completed: true)
         end
      end
    end

    category_list = params[:category_list].to_s.split(",")
    if @article.save
      @article.save_categories(category_list)
    else
      flash[:notice] = 'Article can not successfully created.'
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article= Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
    category_list = params[:category_list].to_s.split(",")
    if @article.update_attributes(article_params)
      @article.save_categories(category_list)
    else
      flash[:notice] = 'Article can not successfully updated.'
    end

    if @article.update(article_params)
        if params[:button1]
           @article.update(is_completed: true)
         elsif params[:button2]
          @article.update(is_completed: false)
         end
      end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ajax_article_list
    # search_by_nameはmodelに定義してあると思ってください
    @articles = Article.search_by_title(params[:q])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_article_tags_to_gon
      gon.article_tags = @article.categories.pluck(&:category_name)
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :error_name, :introduction, :factor, :result, :reference)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_list.html.erb
<table>
  <thead>
    <tr>
      <th>投稿日時</th>
      <th>実装内容</th>
      <th>エラー表記</th>
      <th>言語</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.created_at %></td>
        <td><%= article.title %></td>
        <td><%= article.error_name %></td>
        <td><%= article.categories.pluck(:category_name).join(",") %></td>
        <td>コメント：<%= article.comments.count %></td>
        <td><%= link_to 'Click!', article, class: "btn btn-default sideby" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= article.errors.count %>件のエラーが発生しました <!-- prohibited this article from being saved -->:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-sm-5">
      <div class="form_group">
        <%= form.label :title, "実装内容(必須)" %>
        <%= form.text_field :title, placeholder: "ex)タグ検索機能追加", class: "form-control" %>
      </div>

      <div class="article-tags-field form_group">
        <%= form.label :categories,"言語" %>
        <ul id="article-tags"></ul>
      </div>

      <div class="form_group">
        <%= form.label :error_name, "エラー表記(必須)" %>
        <%= form.text_field :error_name,placeholder: "ex)NoMethodError", class: "form-control" %>
      </div>

      <div class="form_group">
        <%= form.label :factor,"原因(必須)" %>
        <%= form.text_area :factor, placeholder: "マークダウン方式にて記入", rows: 15, class: "form-control" %>
      </div>

      <div class="form_group">
        <%= form.label :reference,"参考URL" %>
        <%= form.text_field :reference, placeholder: "ex) https://qiita.com/xxxxx/xxxxxx", class: "form-control" %>
      </div>
    </div>


    <div class="col-sm-6">
      <div class="form_group">
        <%= form.label :introduction,"実装方法(必須)" %>
        <%= form.text_area :introduction, placeholder: "マークダウン方式にて記入", rows: 14, class: "form-control" %>
      </div>

      <div class="form_group">
        <%= form.label :result,"解決方法(必須)" %>
        <%= form.text_area :result, placeholder: "マークダウン方式にて記入", rows: 12, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-9"></div>

    <div class="col-sm-3">
      <div class="actions">
        <%= form.submit "保存" ,name:"button1",class: 'btn btn-default sideby' %>
        <%= form.submit "一時保存" ,name:"button2",class: 'btn btn-default sideby' %>
        <%= link_to '戻る', articles_path,class: 'btn btn-default sideby' %>
      </div>
    </div>
    <% end %>
  </div>

app/views/articles/_index.html.erb
<table>
  <thead>
    <tr>
      <th>投稿日時</th>
      <th>実装内容</th>
      <th>エラー表記</th>
      <th>言語</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% articles.each do |article| %>
      <tr>
        <td><%= article.created_at %></td>
        <td><%= article.title %></td>
        <td><%= article.error_name %></td>
        <td><%= article.categories.pluck(:category_name).join(",") %></td>
        <td>コメント：<%= article.comments.count %></td>
        <td><%= link_to '詳細', article, class: "btn btn-default sideby" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/ajax_article_list.js.erb
$("#article_list").html("<%= escape_javascript(render 'article_list', articles: @articles) %>");

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
  	<h1>記録を編集しよう!!</h1>
  	<%= render 'form', article: @article %>
  </div>

</div>

app/views/articles/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-2"></div>
		<div class="col-lg-7 text-center">
			<div class="noresult" v-else></div>
			<p>実装内容で検索してみよう！</p>
				<input id="inc_search" type="text">
		</div>
	</div>

	<div class="row">
			<h1>記事一覧
				<%= link_to ' ', new_article_path, class: "glyphicon glyphicon-pencil" %>
			</h1>
			<div id='article_list'>
				<%= render 'index', articles: @articles%>
			</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <h3>エラーを解決したら記録しよう!!</h3>
    <%= render 'form', article: @article %>
  </div>

</div>

app/views/articles/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<div class="container">
  <div class="row">
    <div class="category-link">
    <% unless @article.categories.blank? %>
       <!-- <ul> -->クリック! -->
      <% @article.categories.each do |category| %>
<!--       <li> -->
        <%= link_to category.category_name,articles_path(category_id:category.id),class: 'btn btn-default sideby' %>
<!--       </li> -->
      <% end %>
<!--     </ul> -->
    <% end %>
  </div>

    <div class="row article_show">
    <div class="col-sm-5">
      <div class="form_text">
        <strong>実装内容:</strong>
        <p><%= @article.title %></p>
      </div>

      <div class="form_text">
        <strong>エラー表記:</strong>
        <p><%= @article.error_name %></p>
      </div>

      <div class="form_text">
        <strong>参考URL:</strong>
        <p><%= @article.reference %></p>
      </div>

      <div class="form_area">
        <strong>原因:</strong>
<!--         <%= @article.factor %> -->
        <%= markdown(@article.factor).html_safe %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form_area">
        <strong>実装方法:</strong>
<!--         <%= @article.introduction %> -->
        <%= markdown(@article.introduction).html_safe %>
      </div>

      

      <div class="form_area">
        <strong>解決方法:</strong>
<!--         <%= @article.result %> -->
        <%= markdown(@article.result).html_safe %>
      </div>
    </div>
    </div>

    <div class="row">
      <div class="col-sm-7">
        <strong>コメント:</strong>
        <%= @article.comments.count %>
      <div class="comment-form">
        <%= form_for [@article, @comment] do |f| %>
        <%= f.text_area :comment, size: "50x5" %>
        <%= f.submit '送信',class: 'btn btn-default sideby' %>
        <% end %>
      </div>

      
      
      </div>

      <div class="col-sm-5">
        <table>
        <% @comments.each do |comment| %>
        <tr>
          <td><%= link_to user_path(comment.user), class: "user_#{comment.user.id}" do %>
              <%= attachment_image_tag comment.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", class: "comment_image", style: " text-align: center;" %><br>
              <%= comment.user.name %><% end %></td>

          <td><%= comment.comment %></td>

          <% unless current_user != comment.user %>
          <td><%= link_to '削除', article_comments_path(comment.id),class: 'btn btn-default sideby', method: :delete %></td>
          <% end %>
        </tr>
        <% end %>
      </table>

      
    </div>
  </div>
</div>


<%= link_to "記事一覧", articles_path %> |
<%= link_to 'マイページ', user_path(current_user) %>