config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :articles do
  	resource :comments, only: [:create, :destroy]
    collection do
      get  :ajax_article_list
    end
  end
  get '/top' => 'homes#top'
  get '/about' => 'homes#about'
  root 'homes#top'

  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many  :articles , dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image

  validates :name, length: {maximum: 20, minimum: 2}
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(current_user.id)
		@articles = @user.articles
		@articles = Article.where(user_id: current_user.id).page(params[:page]).reverse_order
	end

	def edit
		@user = User.find(current_user.id)
	end

  def update
  	@user = User.find(current_user.id)
  	if @user.update(user_params)
  		redirect_to user_path, notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end
  def index
    @users = User.all
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>ユーザー</th>
						<th colspan="3"></th>
					</tr>
					</thead>
					<tbody>
						<% users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></td>
							<td><%= user.name%></td>
						</tr>
						<% end %>
					</tbody>
				</table>
				<!--users一覧 -->

app/views/users/_profile.html.erb
<div class="row">
	<div class="col-lg-2">
		<%= attachment_image_tag user, :profile_image, format: "jpeg", id: "img_prev", fallback: "no_image.jpg", class: "profile_image", style: " text-align: center;" %>
	</div>

	<div class="col-lg-7">
		<p class="text-right">
			<%= link_to 'プロフィール',edit_user_path(user), class: "btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
		</p>


		<table>
			<tr>
				<th>ユーザー<span class="glyphicon glyphicon-chevron-right"></span></th>
				<th><%= user.name %></th>
			</tr>

			<tr>
				<th>メモ数<span class="glyphicon glyphicon-chevron-right"></span></th>
				<th><%= user.articles.count %></th>
			</tr>
		</table>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container mypage">
  <div class="row">

<h2>ユーザー情報</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
  <h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :name, class: "name" %>
</div>

<div class="field">
  <%= f.label :image %>
  <%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
    <%= f.label :email, 'メールアドレス' %><br />
    <%= f.email_field :email, class: "email" %>
  </div>

<div class="actions get-button">
    <%= f.submit "編集内容を保存する" ,class: 'btn btn-default sideby' %>
  </div>

<% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<%= render 'index', users: @users%>
			</div>
		</div>
	</div>

app/views/users/show.html.erb
<div class="container mypage">
	<div class="row">
		<%= render 'users/profile', user: @user %>
	</div>

	<div class="row mypage-visual">
		<% if user_signed_in? %>
			<div class="search-form" style=" text-align: center;">
				<%= form_tag(search_path, method: :get) do %>
				<%= text_field_tag 'search[content]' %>
				<%= select_tag 'search[model]',options_for_select({ "ユーザー" => "user", "記事" => "articles" }) %>
				<%= submit_tag '検索' %>
				<% end %>
			<% end %>
			</div>
	</div>

	<div class="row">
		<table>
			<thead>
				<tr>
					<th>実装内容</th>
					<th>エラー表記</th>
					<th>言語</th>
					<th colspan="2"></th>
					<th>
						<% if @user.id == current_user.id %>
			<%= link_to "記録する", new_article_path, class: "btn btn-default glyphicon glyphicon-pencil" %>
			<% end %></th>
				</tr>
			</thead>
				<% @articles.each do |article| %>
			<tbody>
				<tr>
					<td><%= link_to article.title, article, class: "article_#{article.id}" %></td>
					<td><%= article.error_name %></td>
					<td><%= article.categories.pluck(:category_name).join(",") %></td>

					<td>
						<% if article.is_completed == true %>
							投稿済み
						<% else %>
							一時保存中
						<% end %>
					</td>
					<% if @user.id == current_user.id %>
					<td><%= link_to '編集', edit_article_path(article), class: "btn btn-default sideby" %></td>
					<td><%= link_to "削除",article, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-default destroy_article_#{article.id}" %></td><% end %>
					<td></td>
					<td></td>
				</tr>
			</tbody>

			<% end %>
		</table>
		<%= paginate @articles %>
	</div>
</div>