config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :articles do
  	resource :comments, only: [:create, :destroy]
    collection do
      get  :ajax_article_list
    end
  end
  get '/top' => 'homes#top'
  get '/about' => 'homes#about'
  root 'homes#top'

  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostBugs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon(:init => true) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>


    <nav class="navbar navbar-expand">
     <div class="container">
      <div class="naavbar-header">
        <div class="navbar-brand">
          <%= link_to "PostBugs", root_path %></div>
      </div>
          <!-- flashメッセージ表示 -->
      <div id="sp-menu">
       <% if user_signed_in? %>
        <ul>
          <li>ようこそ <%= current_user.name %> さん！</li>
          <li><%= link_to "ABOUT", about_path %></li>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "記事一覧", articles_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"  %></li>
        </ul>
      <% else %>
        <ul>
          <li>ようこそ ゲストさん！</li>
          <li><%= link_to "TOP", top_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
          <li>
            <%= link_to "ログイン", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
        </ul>
      <% end %>
    </div>
        <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
    </div>
    </nav>
  </header>

  <body>
    <%= yield %>
    <div class="navbar-notice">
            <% if flash[:notice] %>
              <p><%= flash[:notice]%></p>
            <% end %>
          </div>
  </body>
</html>